-- ============================================================
-- PRYVIA — SQL ANALYSIS
-- ============================================================
-- Purpose:
-- Analyze experiment performance using PostgreSQL.
--
-- Experiment randomization unit:
-- USER
--
-- Primary metric:
-- Successful Search Rate (SSR)
--
-- Supporting metrics:
-- CTR, reformulation rate, dwell time,
-- search error rate, search latency,
-- and search abandonment.
--
-- Important:
-- SSR is calculated at SEARCH level here for descriptive analysis.
-- Final statistical inference is performed in Python using
-- USER-level aggregation.
-- ============================================================


-- ============================================================
-- 1. EXPERIMENT SAMPLE SIZE
-- ============================================================
-- Count users assigned to each variant.

SELECT
    variant,
    COUNT(*) AS users
FROM experiment_assignments
GROUP BY variant
ORDER BY variant;


-- ============================================================
-- 2. SEARCH VOLUME BY VARIANT
-- ============================================================
-- Count total searches generated by each experiment variant.
--
-- Variant is assigned at USER level, so we connect:
-- searches → sessions → experiment assignments.

SELECT
    ea.variant,
    COUNT(*) AS total_searches
FROM searches s
JOIN search_sessions ss
    ON s.session_id = ss.session_id
JOIN experiment_assignments ea
    ON ss.user_id = ea.user_id
GROUP BY ea.variant
ORDER BY ea.variant;


-- ============================================================
-- 3. CLICK-THROUGH RATE (CTR)
-- ============================================================
-- CTR here is calculated at RESULT level:
--
-- CTR = clicked results / total displayed results
--
-- Each search displays 5 results.

SELECT
    ea.variant,

    COUNT(sr.result_id) AS total_results,

    SUM(
        CASE
            WHEN sr.clicked = TRUE
            THEN 1
            ELSE 0
        END
    ) AS clicked_results,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN sr.clicked = TRUE
                THEN 1
                ELSE 0
            END
        )
        / COUNT(sr.result_id),
        2
    ) AS ctr_percent

FROM search_results sr

JOIN searches s
    ON sr.search_id = s.search_id

JOIN search_sessions ss
    ON s.session_id = ss.session_id

JOIN experiment_assignments ea
    ON ss.user_id = ea.user_id

GROUP BY ea.variant
ORDER BY ea.variant;


-- ============================================================
-- 4. SUCCESSFUL SEARCH RATE (SSR)
-- ============================================================
-- A search is successful when:
--
-- 1. At least one result was clicked.
-- 2. The clicked result had dwell time >= 30 seconds.
-- 3. The search was NOT a reformulation.
--
-- We first reduce result rows to one row per search.

WITH search_level AS (

    SELECT
        s.search_id,
        ea.variant,
        s.is_reformulation,

        MAX(
            CASE
                WHEN sr.clicked = TRUE
                     AND sr.dwell_time_seconds >= 30
                THEN 1
                ELSE 0
            END
        ) AS has_quality_click

    FROM searches s

    JOIN search_sessions ss
        ON s.session_id = ss.session_id

    JOIN experiment_assignments ea
        ON ss.user_id = ea.user_id

    LEFT JOIN search_results sr
        ON s.search_id = sr.search_id

    GROUP BY
        s.search_id,
        ea.variant,
        s.is_reformulation
)

SELECT
    variant,

    COUNT(*) AS total_searches,

    SUM(
        CASE
            WHEN has_quality_click = 1
                 AND is_reformulation = FALSE
            THEN 1
            ELSE 0
        END
    ) AS successful_searches,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN has_quality_click = 1
                     AND is_reformulation = FALSE
                THEN 1
                ELSE 0
            END
        )
        / COUNT(*),
        2
    ) AS ssr_percent

FROM search_level

GROUP BY variant
ORDER BY variant;


-- ============================================================
-- 5. SSR LIFT
-- ============================================================
-- Compare Treatment SSR with Control SSR.
--
-- Absolute lift:
-- Treatment SSR - Control SSR
--
-- Relative improvement:
-- Absolute lift / Control SSR × 100

WITH search_level AS (

    SELECT
        s.search_id,
        ea.variant,
        s.is_reformulation,

        MAX(
            CASE
                WHEN sr.clicked = TRUE
                     AND sr.dwell_time_seconds >= 30
                THEN 1
                ELSE 0
            END
        ) AS has_quality_click

    FROM searches s

    JOIN search_sessions ss
        ON s.session_id = ss.session_id

    JOIN experiment_assignments ea
        ON ss.user_id = ea.user_id

    LEFT JOIN search_results sr
        ON s.search_id = sr.search_id

    GROUP BY
        s.search_id,
        ea.variant,
        s.is_reformulation
),

variant_ssr AS (

    SELECT
        variant,
        COUNT(*) AS total_searches,

        SUM(
            CASE
                WHEN has_quality_click = 1
                     AND is_reformulation = FALSE
                THEN 1
                ELSE 0
            END
        ) AS successful_searches

    FROM search_level

    GROUP BY variant
),

ssr_rates AS (

    SELECT
        variant,
        total_searches,
        successful_searches,

        100.0 *
        successful_searches
        / total_searches AS ssr_percent

    FROM variant_ssr
)

SELECT

    MAX(
        CASE
            WHEN variant = 'Control'
            THEN ssr_percent
        END
    ) AS control_ssr_percent,

    MAX(
        CASE
            WHEN variant = 'Treatment'
            THEN ssr_percent
        END
    ) AS treatment_ssr_percent,

    MAX(
        CASE
            WHEN variant = 'Treatment'
            THEN ssr_percent
        END
    )
    -
    MAX(
        CASE
            WHEN variant = 'Control'
            THEN ssr_percent
        END
    ) AS absolute_lift_percentage_points,

    ROUND(
        100.0 *
        (
            MAX(
                CASE
                    WHEN variant = 'Treatment'
                    THEN ssr_percent
                END
            )
            -
            MAX(
                CASE
                    WHEN variant = 'Control'
                    THEN ssr_percent
                END
            )
        )
        /
        MAX(
            CASE
                WHEN variant = 'Control'
                THEN ssr_percent
            END
        ),
        2
    ) AS relative_improvement_percent

FROM ssr_rates;


-- ============================================================
-- 6. REFORMULATION RATE
-- ============================================================
-- Reformulation rate =
-- reformulated searches / total searches.
--
-- Reformulation is defined as another search within 300 seconds
-- in the same session.

SELECT
    ea.variant,

    COUNT(*) AS total_searches,

    SUM(
        CASE
            WHEN s.is_reformulation = TRUE
            THEN 1
            ELSE 0
        END
    ) AS reformulated_searches,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN s.is_reformulation = TRUE
                THEN 1
                ELSE 0
            END
        )
        / COUNT(*),
        2
    ) AS reformulation_rate_percent

FROM searches s

JOIN search_sessions ss
    ON s.session_id = ss.session_id

JOIN experiment_assignments ea
    ON ss.user_id = ea.user_id

GROUP BY ea.variant
ORDER BY ea.variant;


-- ============================================================
-- 7. DWELL TIME
-- ============================================================
-- Analyze dwell time for clicked results.
--
-- Both average and median are shown because dwell time can
-- contain unusually high values.

SELECT
    ea.variant,

    COUNT(*) AS clicked_results,

    ROUND(
        AVG(sr.dwell_time_seconds)::numeric,
        2
    ) AS avg_dwell_seconds,

    ROUND(
        PERCENTILE_CONT(0.50)
        WITHIN GROUP (
            ORDER BY sr.dwell_time_seconds
        )::numeric,
        2
    ) AS median_dwell_seconds

FROM search_results sr

JOIN searches s
    ON sr.search_id = s.search_id

JOIN search_sessions ss
    ON s.session_id = ss.session_id

JOIN experiment_assignments ea
    ON ss.user_id = ea.user_id

WHERE sr.clicked = TRUE

GROUP BY ea.variant
ORDER BY ea.variant;


-- ============================================================
-- 8. SEARCH ERROR RATE
-- ============================================================
-- Error rate =
-- searches with search_error = TRUE / total searches.
--
-- This is a technical guardrail.

SELECT
    ea.variant,

    COUNT(*) AS total_searches,

    SUM(
        CASE
            WHEN s.search_error = TRUE
            THEN 1
            ELSE 0
        END
    ) AS error_searches,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN s.search_error = TRUE
                THEN 1
                ELSE 0
            END
        )
        / COUNT(*),
        2
    ) AS error_rate_percent

FROM searches s

JOIN search_sessions ss
    ON s.session_id = ss.session_id

JOIN experiment_assignments ea
    ON ss.user_id = ea.user_id

GROUP BY ea.variant
ORDER BY ea.variant;


-- ============================================================
-- 9. SEARCH LATENCY
-- ============================================================
-- Compare average and median search latency.
--
-- Latency is a technical guardrail.

SELECT
    ea.variant,

    COUNT(*) AS total_searches,

    ROUND(
        AVG(s.search_latency_ms)::numeric,
        2
    ) AS avg_latency_ms,

    ROUND(
        PERCENTILE_CONT(0.50)
        WITHIN GROUP (
            ORDER BY s.search_latency_ms
        )::numeric,
        2
    ) AS median_latency_ms

FROM searches s

JOIN search_sessions ss
    ON s.session_id = ss.session_id

JOIN experiment_assignments ea
    ON ss.user_id = ea.user_id

GROUP BY ea.variant
ORDER BY ea.variant;


-- ============================================================
-- 10. SEARCH ABANDONMENT
-- ============================================================
-- A search is considered abandoned when it does not produce
-- a quality click.
--
-- Quality click:
-- clicked result + dwell time >= 30 seconds.

WITH search_level AS (

    SELECT
        s.search_id,
        ea.variant,

        MAX(
            CASE
                WHEN sr.clicked = TRUE
                     AND sr.dwell_time_seconds >= 30
                THEN 1
                ELSE 0
            END
        ) AS has_quality_click

    FROM searches s

    JOIN search_sessions ss
        ON s.session_id = ss.session_id

    JOIN experiment_assignments ea
        ON ss.user_id = ea.user_id

    LEFT JOIN search_results sr
        ON s.search_id = sr.search_id

    GROUP BY
        s.search_id,
        ea.variant
)

SELECT
    variant,

    COUNT(*) AS total_searches,

    SUM(
        CASE
            WHEN has_quality_click = 0
            THEN 1
            ELSE 0
        END
    ) AS abandoned_searches,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN has_quality_click = 0
                THEN 1
                ELSE 0
            END
        )
        / COUNT(*),
        2
    ) AS abandonment_rate_percent

FROM search_level

GROUP BY variant
ORDER BY variant;