-- ============================================================
-- PRYVIA — PostgreSQL Database Schema
-- ============================================================
-- Database: pryvia_analytics
--
-- Core experiment data model:
-- users
-- experiments
-- experiment_assignments
-- search_sessions
-- searches
-- search_results
-- business_events
--
-- Randomization unit:
-- USER
-- ============================================================


-- ============================================================
-- 1. USERS
-- ============================================================

CREATE TABLE users (
    user_id BIGINT PRIMARY KEY,

    user_type VARCHAR(20) NOT NULL,

    device_type VARCHAR(20) NOT NULL,

    country VARCHAR(50) NOT NULL,

    activity_level VARCHAR(20) NOT NULL,

    signup_date DATE NOT NULL
);


-- ============================================================
-- 2. EXPERIMENTS
-- ============================================================

CREATE TABLE experiments (
    experiment_id INTEGER PRIMARY KEY,

    experiment_name VARCHAR(100) NOT NULL,

    start_date DATE NOT NULL,

    end_date DATE,

    allocation_ratio DECIMAL(5,4) NOT NULL,

    primary_metric VARCHAR(50) NOT NULL
);


-- ============================================================
-- 3. EXPERIMENT ASSIGNMENTS
-- ============================================================
-- Stores the experiment variant assigned to each user.
--
-- A user can have only one assignment per experiment.

CREATE TABLE experiment_assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    experiment_id INTEGER NOT NULL,

    user_id BIGINT NOT NULL,

    variant VARCHAR(20) NOT NULL,

    CONSTRAINT fk_assignment_experiment
        FOREIGN KEY (experiment_id)
        REFERENCES experiments(experiment_id),

    CONSTRAINT fk_assignment_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT uq_experiment_user
        UNIQUE (experiment_id, user_id)
);


-- ============================================================
-- 4. SEARCH SESSIONS
-- ============================================================
-- Groups searches performed during a user session.

CREATE TABLE search_sessions (
    session_id BIGINT PRIMARY KEY,

    user_id BIGINT NOT NULL,

    session_start TIMESTAMP NOT NULL,

    session_end TIMESTAMP,

    CONSTRAINT fk_session_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);


-- ============================================================
-- 5. SEARCHES
-- ============================================================
-- One row represents one search performed by a user.

CREATE TABLE searches (
    search_id BIGINT PRIMARY KEY,

    session_id BIGINT NOT NULL,

    query_text TEXT NOT NULL,

    query_category VARCHAR(30) NOT NULL,

    search_timestamp TIMESTAMP NOT NULL,

    search_latency_ms INTEGER NOT NULL,

    search_error BOOLEAN NOT NULL DEFAULT FALSE,

    -- TRUE when this search is a reformulation of a
    -- previous search within the same session and
    -- within the 300-second rule.
    is_reformulation BOOLEAN,

    CONSTRAINT fk_search_session
        FOREIGN KEY (session_id)
        REFERENCES search_sessions(session_id)
);


-- ============================================================
-- 6. SEARCH RESULTS
-- ============================================================
-- Stores the ranked results displayed for each search.

CREATE TABLE search_results (
    result_id BIGINT PRIMARY KEY,

    search_id BIGINT NOT NULL,

    rank_position INTEGER NOT NULL,

    result_type VARCHAR(30) NOT NULL,

    relevance_score DECIMAL(5,4) NOT NULL,

    clicked BOOLEAN NOT NULL DEFAULT FALSE,

    dwell_time_seconds DECIMAL(8,2),

    returned_to_search BOOLEAN,

    CONSTRAINT fk_result_search
        FOREIGN KEY (search_id)
        REFERENCES searches(search_id)
);


-- ============================================================
-- 7. BUSINESS EVENTS
-- ============================================================
-- Stores important user/search events such as:
-- click, dwell, success, and reformulation.

CREATE TABLE business_events (
    event_id BIGINT PRIMARY KEY,

    search_id BIGINT NOT NULL,

    event_type VARCHAR(30) NOT NULL,

    event_timestamp TIMESTAMP NOT NULL,

    CONSTRAINT fk_business_event_search
        FOREIGN KEY (search_id)
        REFERENCES searches(search_id)
);